* Journey to the Center of Hawkthorne

This 2d  platformer is  based on  Community's [[http://en.wikipedia.org/wiki/Digital_Estate_Planning][Digital  Estate Planning]]
episode.  It's built  using the  [[https://love2d.org/][LÖVE]] game  engine. Please  [[https://github.com/hawkthorne/hawkthorne-journey/issues?state=open][report any
issues or bugs]] you have with the game!

** Download the game
- [[http://files.projecthawkthorne.com/releases/latest/hawkthorne-osx.zip][OS  X]]
- [[http://files.projecthawkthorne.com/releases/latest/hawkthorne-win-x86.zip][Windows]]

** Contribute to the game

All discussion  and development takes  place on [[http://www.reddit.com/r/hawkthorne][/r/hawkthorne]].  If you
have  any contributions  you'd  like  to submit,  either  open a  pull
request or  create a post on  the subreddit. The steps  below are only
needed if you want to write code for the game.

*** Getting started with development on OS X / Linux

Getting start is easy. Just clone the repository and run =make run=.

#+begin_src sh
$ git clone git://github.com/hawkthorne/hawkthorne-journey.git
$ cd hawkthorne-journey
$ make run
#+end_src

*** Getting started with development on Windows

First, download and install [[http://windows.github.com/][Github for Windows]] which will setup git on
your computer. You'll also  need PowerShell, which comes pre-installed
on Windows 7 & 8.

Once you've  installed and logged  in with  Github for Windows,  go to
=https://github.com/hawkthorne/hawkthorne-journey=  and  click the  =Fork=
button

After   you've    successfully   forked    the   repository    go   to
=https://github.com/<your  username>/hawkthorne-journey=  and click  the
"Clone in Windows" button.

Once you  have the  repo, click  on it in  Github for  Windows, select
"tools > open a shell here".

In your new PowerShell window, run

#+begin_src powershell
> .\make.ps1 run
#+end_src

*** Next steps

Congratulations! You're  running Journey to the  Center of Hawkthorne!
Your next steps can be:

- Fix [[https://github.com/hawkthorne/hawkthorne-journey/issues?labels=bug&state=open][bugs]] with the game
- Add new features and content to the game

** Community
- [[http://www.reddit.com/r/hawkthorne][/r/hawkthorne subreddit]]
- [[http://webchat.freenode.net/?channels=hawkthorne][#hawkthorne@irc.freenode.net]] on IRC

** Releasing a new version

We release a new version of  Journey to the Center of Hawkthorne about
every two  weeks. To create  a release, open  a pull request  from the
=master= branch to the =release=  branch. You should never commit directly
to the =release= branch.

** License

Unless otherwise noted, this code is licensed under the MIT License.

Artwork  and audio  files are  licensed under  [[http://creativecommons.org/licenses/by-nc/3.0/][CC BY-NC  3.0]].  Artwork
includes all .png, .psd, .ogg, and .wav files.
